import Head from "next/head";
import FormSection from "../Components/Signup-stepone/FormSection";
import SignupOnebanner from "../Components/Signup-stepone/SignupStepBanner";
 

export default function SignupOne() {
  return (
    <div  className="signup-step-oneWrapper">
      <Head>
        <title>Create Next App</title>
        <meta name="Sign up step 1" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SignupOnebanner />
      <FormSection/>
    </div>
  )
}